filename = 'build/psp-mac-0.10.0.dmg'
volume_label = 'psp-mac-0.10.0'
format = 'UDZO'
filesystem = 'HFS+'
size = None
files = ['build/Palworld Save Pal.app']
symlinks = {'Applications': '/Applications'}
icon_locations = {'Applications': (500, 120), 'Palworld Save Pal.app': (140, 120)}
icon = '/Users/tristan/Documents/Projects/palworld-save-pal/ui/static/favicon.ico'
background = 'builtin-arrow'
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
window_rect = ((100, 100), (640, 380))
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = 'auto'
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 16
icon_size = 128
icon_locations = {'Applications': (500, 120), 'Palworld Save Pal.app': (140, 120)}
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
