import type { Pal, Player } from './game';

export enum MessageType {
	ADD_PAL = 'add_pal',
	ADD_DPS_PAL = 'add_dps_pal',
	CLONE_PAL = 'clone_pal',
	CLONE_DPS_PAL = 'clone_dps_pal',
	MOVE_PAL = 'move_pal',
	DELETE_PALS = 'delete_pals',
	DELETE_DPS_PALS = 'delete_dps_pals',
	HEAL_PALS = 'heal_pals',
	HEAL_ALL_PALS = 'heal_all_pals',
	DOWNLOAD_SAVE_FILE = 'download_save_file',
	ERROR = 'error',
	WARNING = 'warning',
	GET_GUILDS = 'get_guilds',
	GET_PLAYERS = 'get_players',
	GET_PAL_DETAILS = 'get_pal_details',
	LOAD_ZIP_FILE = 'load_zip_file',
	PROGRESS_MESSAGE = 'progress_message',
	SYNC_APP_STATE = 'sync_app_state',
	UPDATE_SAVE_FILE = 'update_save_file',
	GET_PRESETS = 'get_presets',
	ADD_PRESET = 'add_preset',
	UPDATE_PRESET = 'update_preset',
	DELETE_PRESET = 'delete_preset',
	GET_ACTIVE_SKILLS = 'get_active_skills',
	GET_FRIENDSHIP_DATA = 'get_friendship_data',
	GET_PASSIVE_SKILLS = 'get_passive_skills',
	GET_TECHNOLOGIES = 'get_technologies',
	GET_ELEMENTS = 'get_elements',
	GET_ITEMS = 'get_items',
	GET_PALS = 'get_pals',
	SET_TECHNOLOGY_DATA = 'set_technology_data',
	OPEN_IN_BROWSER = 'open_in_browser',
	OPEN_URL = 'open_url',
	GET_EXP_DATA = 'get_exp_data',
	GET_RELIC_DATA = 'get_relic_data',
	GET_VERSION = 'get_version',
	SELECT_SAVE = 'select_save',
	LOADED_SAVE_FILES = 'loaded_save_files',
	REATTACH_SESSION = 'reattach_session',
	EJECT_SESSION = 'eject_session',
	SESSION_NOT_FOUND = 'session_not_found',
	SAVE_MODDED_SAVE = 'save_modded_save',
	SAVE_EDITED_SAV = 'save_edited_sav',
	GET_SETTINGS = 'get_settings',
	UPDATE_SETTINGS = 'update_settings',
	GET_UI_COMMON = 'get_ui_common',
	NO_FILE_SELECTED = 'no_file_selected',
	SELECT_GAMEPASS_SAVE = 'select_gamepass_save',
	GET_SAVE_TYPE = 'get_save_type',
	GET_WORK_SUITABILITY = 'get_work_suitability',
	GET_BUILDINGS = 'get_buildings',
	GET_RAW_DATA = 'get_raw_data',
	GET_MAP_OBJECTS = 'get_map_objects',
	GET_BOSSES = 'get_bosses',
	GET_FAST_TRAVEL_POINTS = 'get_fast_travel_points',
	GET_RELICS = 'get_relics',
	DELETE_GUILD = 'delete_guild',
	DELETE_PLAYER = 'delete_player',
	NUKE_PRESETS = 'nuke_presets',
	EXPORT_PRESET = 'export_preset',
	IMPORT_PRESET = 'import_preset',
	EXPORT_PRESETS = 'export_presets',
	GET_LAB_RESEARCH = 'get_lab_research',
	UPDATE_LAB_RESEARCH = 'update_lab_research',
	RENAME_WORLD = 'rename_world',
	ADD_GPS_PAL = 'add_gps_pal',
	CLONE_GPS_PAL = 'clone_gps_pal',
	DELETE_GPS_PALS = 'delete_gps_pals',
	UPDATE_GPS_PAL = 'update_gps_pal',
	GET_GPS_PALS = 'get_gps_pals',

	// UPS (Universal Pal Storage) Messages
	GET_UPS_PALS = 'get_ups_pals',
	GET_UPS_ALL_FILTERED_IDS = 'get_ups_all_filtered_ids',
	ADD_UPS_PAL = 'add_ups_pal',
	UPDATE_UPS_PAL = 'update_ups_pal',
	DELETE_UPS_PALS = 'delete_ups_pals',
	CLONE_UPS_PAL = 'clone_ups_pal',
	CLONE_TO_UPS = 'clone_to_ups',
	EXPORT_UPS_PAL = 'export_ups_pal',
	CLONE_GPS_PAL_TO_PLAYER = 'clone_gps_pal_to_player',
	IMPORT_TO_UPS = 'import_to_ups',
	GET_UPS_COLLECTIONS = 'get_ups_collections',
	CREATE_UPS_COLLECTION = 'create_ups_collection',
	UPDATE_UPS_COLLECTION = 'update_ups_collection',
	DELETE_UPS_COLLECTION = 'delete_ups_collection',
	GET_UPS_TAGS = 'get_ups_tags',
	CREATE_UPS_TAG = 'create_ups_tag',
	UPDATE_UPS_TAG = 'update_ups_tag',
	DELETE_UPS_TAG = 'delete_ups_tag',
	GET_UPS_STATS = 'get_ups_stats',
	NUKE_UPS_PALS = 'nuke_ups_pals',

	// Map
	UNLOCK_MAP = 'unlock_map',
	GET_PLAYER_SUMMARIES = 'get_player_summaries',
	GET_GUILD_SUMMARIES = 'get_guild_summaries',
	GET_PAL_SUMMARIES = 'get_pal_summaries',
	REQUEST_PLAYER_DETAILS = 'request_player_details',
	GET_PLAYER_DETAILS_RESPONSE = 'get_player_details_response',
	REQUEST_GUILD_DETAILS = 'request_guild_details',
	GET_GUILD_DETAILS_RESPONSE = 'get_guild_details_response',
	REQUEST_GPS = 'request_gps',
	GET_GPS_RESPONSE = 'get_gps_response',
	GET_MISSIONS = 'get_missions',

	OPEN_FOLDER = 'open_folder',
	CONVERT_SAV_FILE = 'convert_sav_file',
	CONVERT_SAVE_FORMAT = 'convert_save_format',
	SCAN_GAMEPASS_SAVES = 'scan_gamepass_saves',
	DELETE_GAMEPASS_SAVE = 'delete_gamepass_save',
	DELETE_GAMEPASS_PLAYER = 'delete_gamepass_player',
	RENAME_GAMEPASS_WORLD = 'rename_gamepass_world',

	// Tools
	CONVERT_STEAM_ID = 'convert_steam_id',
	SWAP_PLAYER_UIDS = 'swap_player_uids',
	LOAD_SOURCE_SAVE = 'load_source_save',
	GET_SOURCE_PLAYERS = 'get_source_players',
	TRANSFER_PLAYER = 'transfer_player',
	UNLOAD_SOURCE_SAVE = 'unload_source_save',

	// Server Management
	LIST_SERVERS = 'list_servers',
	GET_SERVER = 'get_server',
	CREATE_SERVER = 'create_server',
	UPDATE_SERVER = 'update_server',
	DELETE_SERVER = 'delete_server',
	START_SERVER = 'start_server',
	STOP_SERVER = 'stop_server',
	SERVER_STATUS_UPDATE = 'server_status_update',
	SERVER_API_CALL = 'server_api_call',
	SERVER_API_RESPONSE = 'server_api_response',
	SERVER_PLAYER_COUNT = 'server_player_count',
	LIST_SERVER_MODS = 'list_server_mods',
	TOGGLE_SERVER_MOD = 'toggle_server_mod',
	INSTALL_SERVER_MOD = 'install_server_mod',
	DETECT_WORKSHOP_DIR = 'detect_workshop_dir',
	LOAD_SERVER_SAVE = 'load_server_save',
	GET_SERVER_STATS = 'get_server_stats',
	SERVER_CREATION_PROGRESS = 'server_creation_progress',
	IMPORT_SERVER = 'import_server',

	// World Options
	GET_WORLD_OPTION = 'get_world_option',
	UPDATE_WORLD_OPTION = 'update_world_option'
}

interface UpdateSaveFileData {
	modifiedPals: Record<string, Pal>;
	modifiedPlayers: Record<string, Player>;
}

export interface Message {
	type: MessageType;
	data?: any | UpdateSaveFileData;
}
