[package]
name = "ps-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PalStudio Lua plugin runtime and hook system"
repository = "https://github.com/oMaN-Rod/palworld-save-pal"
autobenches = false

[dependencies]
chrono.workspace = true
ps-core.workspace = true
ps-lua-sys.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ps-core = { workspace = true, features = ["oodle"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[test]]
name = "hook_interval"
path = "benches/hook_interval.rs"
