from typing import TYPE_CHECKING

from palworld_save_pal.ws.handlers import (
    active_skills_handler,
    app_state_handler,
    buildings_handler,
    convert_handler,
    debug_handler,
    elements_handler,
    exp_handler,
    friendship_handler,
    guild_handler,
    items_handler,
    lab_research_handler,
    lazy_load_handler,
    map_objects_handler,
    map_unlock_handler,
    missions_handler,
    open_in_browser_handler,
    passive_skills_handler,
    player_handler,
    technologies_handler,
    preset_handler,
    save_file_handler,
    pal_handler,
    settings_handler,
    steam_id_handler,
    transfer_handler,
    uid_swap_handler,
    ui_common_handler,
    version_handler,
    local_file_handler,
    work_suitability_handler,
    gps_handler,
    ups_handler,
    server_handler,
)
from palworld_save_pal.ws.messages import (
    AddDpsPalMessage,
    AddPalMessage,
    AddPresetMessage,
    BaseMessage,
    CloneDpsPalMessage,
    ClonePalMessage,
    DeleteDpsPalsMessage,
    DeleteGpsPalsMessage,
    DeleteGuildMessage,
    DeletePlayerMessage,
    ExportPresetMessage,
    GetActiveSkillsMessage,
    GetBuildingsMessage,
    GetElementsMessage,
    GetItemsMessage,
    GetLabResearchMessage,
    GetMapObjectsMessage,
    GetMissionsMessage,
    GetPalsMessage,
    GetPassiveSkillsMessage,
    GetRawDataMessage,
    GetSettingsMessage,
    GetTechnologiesMessage,
    GetWorkSuitabilityMessage,
    HealAllPalsMessage,
    HealPalsMessage,
    ImportPresetMessage,
    ConvertSavFileMessage,
    ConvertSaveFormatMessage,
    DeleteGamepassPlayerMessage,
    DeleteGamepassSaveMessage,
    MessageType,
    RenameGamepassWorldMessage,
    ScanGamepassSavesMessage,
    MovePalMessage,
    NukePresetsMessage,
    OpenInBrowserMessage,
    RenameWorldMessage,
    SelectGamepassSaveMessage,
    SetTechnologyDataMessage,
    SyncAppStateMessage,
    UpdateLabResearchMessage,
    UpdateSaveFileMessage,
    DownloadSaveFileMessage,
    LoadZipFileMessage,
    DeletePalsMessage,
    GetPresetsMessage,
    DeletePresetMessage,
    UpdatePresetMessage,
    GetVersionMessage,
    SelectSaveMessage,
    UpdateSettingsMessage,
    AddGpsPalMessage,
    # UPS Messages
    GetUpsPalsMessage,
    GetUpsAllFilteredIdsMessage,
    AddUpsPalMessage,
    UpdateUpsPalMessage,
    DeleteUpsPalsMessage,
    CloneUpsPalMessage,
    CloneToUpsMessage,
    ExportUpsPalMessage,
    ImportToUpsMessage,
    GetUpsCollectionsMessage,
    CreateUpsCollectionMessage,
    UpdateUpsCollectionMessage,
    DeleteUpsCollectionMessage,
    GetUpsTagsMessage,
    CreateUpsTagMessage,
    UpdateUpsTagMessage,
    DeleteUpsTagMessage,
    GetUpsStatsMessage,
    NukeUpsPalsMessage,
    UnlockMapMessage,
    RequestPlayerDetailsMessage,
    RequestGuildDetailsMessage,
    RequestGpsMessage,
    # Server Management Messages
    ListServersMessage,
    GetServerMessage,
    CreateServerMessage,
    UpdateServerMessage,
    DeleteServerMessage,
    StartServerMessage,
    StopServerMessage,
    ServerApiCallMessage,
    ListServerModsMessage,
    ToggleServerModMessage,
    InstallServerModMessage,
    DetectWorkshopDirMessage,
    LoadServerSaveMessage,
    GetServerStatsMessage,
    ConvertSteamIdMessage,
    SwapPlayerUidsMessage,
    LoadSourceSaveMessage,
    GetSourcePlayersMessage,
    TransferPlayerMessage,
    UnloadSourceSaveMessage,
)

if TYPE_CHECKING:
    from palworld_save_pal.ws.dispatcher import MessageDispatcher

HANDLER_REGISTRY = [
    # Save file
    (MessageType.DOWNLOAD_SAVE_FILE, DownloadSaveFileMessage, save_file_handler.download_save_file_handler),
    (MessageType.LOAD_ZIP_FILE, LoadZipFileMessage, save_file_handler.load_zip_file_handler),
    (MessageType.UPDATE_SAVE_FILE, UpdateSaveFileMessage, save_file_handler.update_save_file_handler),
    # App state
    (MessageType.SYNC_APP_STATE, SyncAppStateMessage, app_state_handler.sync_app_state_handler),
    # Pals
    (MessageType.GET_PALS, GetPalsMessage, pal_handler.get_pals_handler),
    (MessageType.DELETE_PALS, DeletePalsMessage, pal_handler.delete_pals_handler),
    (MessageType.DELETE_DPS_PALS, DeleteDpsPalsMessage, pal_handler.delete_dps_pals_handler),
    (MessageType.HEAL_PALS, HealPalsMessage, pal_handler.heal_pals_handler),
    (MessageType.HEAL_ALL_PALS, HealAllPalsMessage, pal_handler.heal_all_pals_handler),
    (MessageType.ADD_PAL, AddPalMessage, pal_handler.add_pal_handler),
    (MessageType.ADD_DPS_PAL, AddDpsPalMessage, pal_handler.add_dps_pal_handler),
    (MessageType.CLONE_PAL, ClonePalMessage, pal_handler.clone_pal_handler),
    (MessageType.CLONE_DPS_PAL, CloneDpsPalMessage, pal_handler.clone_dps_pal_handler),
    (MessageType.MOVE_PAL, MovePalMessage, pal_handler.move_pal_handler),
    # Presets
    (MessageType.ADD_PRESET, AddPresetMessage, preset_handler.add_preset_handler),
    (MessageType.GET_PRESETS, GetPresetsMessage, preset_handler.get_presets_handler),
    (MessageType.UPDATE_PRESET, UpdatePresetMessage, preset_handler.update_preset_handler),
    (MessageType.DELETE_PRESET, DeletePresetMessage, preset_handler.delete_presets_handler),
    (MessageType.NUKE_PRESETS, NukePresetsMessage, preset_handler.nuke_presets_handler),
    (MessageType.EXPORT_PRESET, ExportPresetMessage, preset_handler.export_preset_handler),
    (MessageType.IMPORT_PRESET, ImportPresetMessage, preset_handler.import_preset_handler),
    # Skills & data
    (MessageType.GET_ACTIVE_SKILLS, GetActiveSkillsMessage, active_skills_handler.get_active_skills_handler),
    (MessageType.GET_PASSIVE_SKILLS, GetPassiveSkillsMessage, passive_skills_handler.get_passive_skills_handler),
    (MessageType.GET_TECHNOLOGIES, GetTechnologiesMessage, technologies_handler.get_technologies_handler),
    (MessageType.SET_TECHNOLOGY_DATA, SetTechnologyDataMessage, technologies_handler.set_technology_data_handler),
    (MessageType.GET_ELEMENTS, GetElementsMessage, elements_handler.get_elements_handler),
    (MessageType.GET_ITEMS, GetItemsMessage, items_handler.get_items_handler),
    (MessageType.GET_MISSIONS, GetMissionsMessage, missions_handler.get_missions_handler),
    (MessageType.GET_WORK_SUITABILITY, GetWorkSuitabilityMessage, work_suitability_handler.get_work_suitability_handler),
    (MessageType.GET_EXP_DATA, BaseMessage, exp_handler.get_exp_data_handler),
    (MessageType.GET_FRIENDSHIP_DATA, BaseMessage, friendship_handler.get_friendship_data_handler),
    # Guild & player
    (MessageType.DELETE_GUILD, DeleteGuildMessage, guild_handler.delete_guild_handler),
    (MessageType.DELETE_PLAYER, DeletePlayerMessage, player_handler.delete_player_handler),
    # UI & settings
    (MessageType.OPEN_IN_BROWSER, OpenInBrowserMessage, open_in_browser_handler.open_in_browser_handler),
    (MessageType.GET_VERSION, GetVersionMessage, version_handler.get_version_handler),
    (MessageType.GET_SETTINGS, GetSettingsMessage, settings_handler.get_settings_handler),
    (MessageType.UPDATE_SETTINGS, UpdateSettingsMessage, settings_handler.update_settings_handler),
    (MessageType.GET_UI_COMMON, BaseMessage, ui_common_handler.get_ui_common_handler),
    # Local file & save management
    (MessageType.SELECT_SAVE, SelectSaveMessage, local_file_handler.select_save_files_handler),
    (MessageType.SAVE_MODDED_SAVE, BaseMessage, local_file_handler.save_modded_save_handler),
    (MessageType.SELECT_GAMEPASS_SAVE, SelectGamepassSaveMessage, local_file_handler.select_gamepass_save_handler),
    (MessageType.RENAME_WORLD, RenameWorldMessage, local_file_handler.rename_world_handler),
    (MessageType.CONVERT_SAV_FILE, ConvertSavFileMessage, local_file_handler.convert_sav_file),
    # Buildings, map, debug
    (MessageType.GET_BUILDINGS, GetBuildingsMessage, buildings_handler.get_buildings_handler),
    (MessageType.GET_RAW_DATA, GetRawDataMessage, debug_handler.get_raw_data_handler),
    (MessageType.GET_MAP_OBJECTS, GetMapObjectsMessage, map_objects_handler.get_map_objects_handler),
    (MessageType.UNLOCK_MAP, UnlockMapMessage, map_unlock_handler.unlock_map_handler),
    # Lab research
    (MessageType.GET_LAB_RESEARCH, GetLabResearchMessage, lab_research_handler.get_lab_research_handler),
    (MessageType.UPDATE_LAB_RESEARCH, UpdateLabResearchMessage, lab_research_handler.update_lab_research_handler),
    # GPS
    (MessageType.ADD_GPS_PAL, AddGpsPalMessage, gps_handler.add_gps_pal_handler),
    (MessageType.DELETE_GPS_PALS, DeleteGpsPalsMessage, gps_handler.delete_gps_pals_handler),
    (MessageType.REQUEST_GPS, RequestGpsMessage, gps_handler.request_gps_handler),
    # Lazy loading
    (MessageType.REQUEST_PLAYER_DETAILS, RequestPlayerDetailsMessage, lazy_load_handler.request_player_details_handler),
    (MessageType.REQUEST_GUILD_DETAILS, RequestGuildDetailsMessage, lazy_load_handler.request_guild_details_handler),
    # Convert & Gamepass
    (MessageType.CONVERT_SAVE_FORMAT, ConvertSaveFormatMessage, convert_handler.convert_save_format_handler),
    (MessageType.SCAN_GAMEPASS_SAVES, ScanGamepassSavesMessage, convert_handler.scan_gamepass_saves_handler),
    (MessageType.DELETE_GAMEPASS_SAVE, DeleteGamepassSaveMessage, convert_handler.delete_gamepass_save_handler),
    (MessageType.DELETE_GAMEPASS_PLAYER, DeleteGamepassPlayerMessage, convert_handler.delete_gamepass_player_handler),
    (MessageType.RENAME_GAMEPASS_WORLD, RenameGamepassWorldMessage, convert_handler.rename_gamepass_world_handler),
    # UPS (Universal Pal Storage)
    (MessageType.GET_UPS_PALS, GetUpsPalsMessage, ups_handler.get_ups_pals_handler),
    (MessageType.GET_UPS_ALL_FILTERED_IDS, GetUpsAllFilteredIdsMessage, ups_handler.get_ups_all_filtered_ids_handler),
    (MessageType.ADD_UPS_PAL, AddUpsPalMessage, ups_handler.add_ups_pal_handler),
    (MessageType.UPDATE_UPS_PAL, UpdateUpsPalMessage, ups_handler.update_ups_pal_handler),
    (MessageType.DELETE_UPS_PALS, DeleteUpsPalsMessage, ups_handler.delete_ups_pals_handler),
    (MessageType.CLONE_UPS_PAL, CloneUpsPalMessage, ups_handler.clone_ups_pal_handler),
    (MessageType.CLONE_TO_UPS, CloneToUpsMessage, ups_handler.clone_to_ups_handler),
    (MessageType.EXPORT_UPS_PAL, ExportUpsPalMessage, ups_handler.export_ups_pal_handler),
    (MessageType.IMPORT_TO_UPS, ImportToUpsMessage, ups_handler.import_to_ups_handler),
    (MessageType.GET_UPS_COLLECTIONS, GetUpsCollectionsMessage, ups_handler.get_ups_collections_handler),
    (MessageType.CREATE_UPS_COLLECTION, CreateUpsCollectionMessage, ups_handler.create_ups_collection_handler),
    (MessageType.UPDATE_UPS_COLLECTION, UpdateUpsCollectionMessage, ups_handler.update_ups_collection_handler),
    (MessageType.DELETE_UPS_COLLECTION, DeleteUpsCollectionMessage, ups_handler.delete_ups_collection_handler),
    (MessageType.GET_UPS_TAGS, GetUpsTagsMessage, ups_handler.get_ups_tags_handler),
    (MessageType.CREATE_UPS_TAG, CreateUpsTagMessage, ups_handler.create_ups_tag_handler),
    (MessageType.UPDATE_UPS_TAG, UpdateUpsTagMessage, ups_handler.update_ups_tag_handler),
    (MessageType.DELETE_UPS_TAG, DeleteUpsTagMessage, ups_handler.delete_ups_tag_handler),
    (MessageType.GET_UPS_STATS, GetUpsStatsMessage, ups_handler.get_ups_stats_handler),
    (MessageType.NUKE_UPS_PALS, NukeUpsPalsMessage, ups_handler.nuke_ups_pals_handler),
    # Server Management
    (MessageType.LIST_SERVERS, ListServersMessage, server_handler.list_servers_handler),
    (MessageType.GET_SERVER, GetServerMessage, server_handler.get_server_handler),
    (MessageType.CREATE_SERVER, CreateServerMessage, server_handler.create_server_handler),
    (MessageType.UPDATE_SERVER, UpdateServerMessage, server_handler.update_server_handler),
    (MessageType.DELETE_SERVER, DeleteServerMessage, server_handler.delete_server_handler),
    (MessageType.START_SERVER, StartServerMessage, server_handler.start_server_handler),
    (MessageType.STOP_SERVER, StopServerMessage, server_handler.stop_server_handler),
    (MessageType.SERVER_API_CALL, ServerApiCallMessage, server_handler.server_api_call_handler),
    (MessageType.LIST_SERVER_MODS, ListServerModsMessage, server_handler.list_server_mods_handler),
    (MessageType.TOGGLE_SERVER_MOD, ToggleServerModMessage, server_handler.toggle_server_mod_handler),
    (MessageType.INSTALL_SERVER_MOD, InstallServerModMessage, server_handler.install_server_mod_handler),
    (MessageType.DETECT_WORKSHOP_DIR, DetectWorkshopDirMessage, server_handler.detect_workshop_dir_handler),
    (MessageType.LOAD_SERVER_SAVE, LoadServerSaveMessage, server_handler.load_server_save_handler),
    (MessageType.GET_SERVER_STATS, GetServerStatsMessage, server_handler.get_server_stats_handler),
    # Tools
    (MessageType.CONVERT_STEAM_ID, ConvertSteamIdMessage, steam_id_handler.convert_steam_id_handler),
    (MessageType.SWAP_PLAYER_UIDS, SwapPlayerUidsMessage, uid_swap_handler.swap_player_uids_handler),
    # Player Transfer
    (MessageType.LOAD_SOURCE_SAVE, LoadSourceSaveMessage, transfer_handler.load_source_save_handler),
    (MessageType.GET_SOURCE_PLAYERS, GetSourcePlayersMessage, transfer_handler.get_source_players_handler),
    (MessageType.TRANSFER_PLAYER, TransferPlayerMessage, transfer_handler.transfer_player_handler),
    (MessageType.UNLOAD_SOURCE_SAVE, UnloadSourceSaveMessage, transfer_handler.unload_source_save_handler),
]


def bootstrap(dispatcher: "MessageDispatcher"):
    for message_type, message_class, handler_func in HANDLER_REGISTRY:
        dispatcher.register_handler(
            message_type.value,
            {
                "message_class": message_class,
                "handler_func": handler_func,
            },
        )
